# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161220_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeuser',
            name='subscription_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
